name: Build InsertTools Docker Image

on:
  workflow_run:
    workflows: ["Build ModLoader Package"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download InsertTools
        uses: actions/download-artifact@v4
        with:
          name: insertTools
          run-id: ${{ github.event.workflow_run.id }}
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta Docker Image
        id: insertToolMeta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }}-inserttools
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          file: insertTools.dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.insertToolMeta.outputs.tags }}
          labels: ${{ steps.insertToolMeta.outputs.labels }}
          build-args: |
            BUILDPLATFORM=linux/amd64
